# Generated by Django 4.0.3 on 2022-03-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=50)),
                ('corporate_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('due_date', models.DateField()),
                ('invoice_status', models.CharField(choices=[('no_payment', 'sem pagamento'), ('payment_not_made', 'pagamento não efetuado'), ('payment_made', 'pagamento realizado'), ('payment_received', 'pagamento recebido'), ('payment_canceled', 'pagamento cancelado'), ('payment_processed', 'pagamento processado'), ('payment_in_process', 'pagamento em processamento')], default=('no_payment', 'sem pagamento'), max_length=100)),
                ('accounts_payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.accountspayable')),
                ('accounts_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.accountsreceivable')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('vendor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.vendor')),
                ('holder_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('agency', models.CharField(max_length=15)),
                ('account', models.CharField(max_length=15)),
                ('account_type', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounting.vendor')),
            ],
            bases=('accounting.vendor',),
        ),
    ]
