# Generated by Django 4.0.3 on 2022-03-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nspname', max_length=255)),
                ('nspowner', models.IntegerField()),
                ('nspacl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pg_namespace',
                'managed': False,
            },
        ),
    ]
