version: "3.9"

services:
  database:
    image: postgres
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=update_sem_where
      - POSTGRES_PASSWORD=p4ssw0rd
    ports:
      - 5432:5432
